# Enterprise Data Warehouse for Financial Services

Brief: Build an enterprise data warehouse addressing financial services needs.

- Objectives:
  - Consolidate financial data for reporting, risk, and analytics.
- Scope:
  - Ledgers, transactions, customer data, regulatory reporting.
- Key Components:
  - Data models, ETL, access controls.
- Technologies:
  - Synapse/Redshift/Snowflake, ETL orchestration, cataloging.
- Deliverables:
  - DW implementation, report migration, validation docs.

# Expanded Source Schemas, ER Diagrams, Facts & Dimensions

This standardized expansion provides five logical sources for the project and a canonical set of artifacts to be appended to project markdown files when a detailed schema is required.

NOTE: The artifacts below are design artifacts created for documentation and implementation planning. They are original work and may be used for internal design and implementation purposes.

Project-specific prefix: `enterprise_data_warehouse_for_financial_services` (derived from filename: `enterprise-data-warehouse-for-financial-services.md`).

---

### Source A: Ingest & Landing (Source: `enterprise_data_warehouse_for_financial_services_ingest`)

Tables (20):
1. enterprise_data_warehouse_for_financial_services_stg_raw
2. enterprise_data_warehouse_for_financial_services_raw_records
3. enterprise_data_warehouse_for_financial_services_dim_source_system
4. enterprise_data_warehouse_for_financial_services_dim_data_owner
5. enterprise_data_warehouse_for_financial_services_dim_file_type
6. enterprise_data_warehouse_for_financial_services_ref_file_schema
7. enterprise_data_warehouse_for_financial_services_fact_raw_events
8. enterprise_data_warehouse_for_financial_services_stage_enrichments
9. enterprise_data_warehouse_for_financial_services_dim_geo
10. enterprise_data_warehouse_for_financial_services_dim_business_unit
11. enterprise_data_warehouse_for_financial_services_audit_ingest
12. enterprise_data_warehouse_for_financial_services_dim_environment
13. enterprise_data_warehouse_for_financial_services_ref_parsing_errors
14. enterprise_data_warehouse_for_financial_services_stage_cdc
15. enterprise_data_warehouse_for_financial_services_dim_schema_version
16. enterprise_data_warehouse_for_financial_services_fact_event_counts
17. enterprise_data_warehouse_for_financial_services_audit_transforms
18. enterprise_data_warehouse_for_financial_services_stage_retries
19. enterprise_data_warehouse_for_financial_services_ref_mappings
20. enterprise_data_warehouse_for_financial_services_dim_status

ER Diagram (ASCII):

enterprise_data_warehouse_for_financial_services_fact_raw_events (event_id, source_system_id, record_key, payload_hash, event_ts)
  |-- source_system_id --> enterprise_data_warehouse_for_financial_services_dim_source_system(source_system_id)
  |-- record_key --> enterprise_data_warehouse_for_financial_services_raw_records(record_key)

Description: Ingest staging (immutable) → raw normalization → enrichment → audit. `enterprise_data_warehouse_for_financial_services_fact_raw_events` is used for throughput and source health monitoring.

---

### Source B: Operational Logs & Metrics (Source: `enterprise_data_warehouse_for_financial_services_ops`)

Tables (20):
1. enterprise_data_warehouse_for_financial_services_stg_ops_logs
2. enterprise_data_warehouse_for_financial_services_raw_ops
3. enterprise_data_warehouse_for_financial_services_dim_service
4. enterprise_data_warehouse_for_financial_services_dim_instance
5. enterprise_data_warehouse_for_financial_services_dim_log_level
6. enterprise_data_warehouse_for_financial_services_ref_error_codes
7. enterprise_data_warehouse_for_financial_services_fact_logs
8. enterprise_data_warehouse_for_financial_services_stage_alerts
9. enterprise_data_warehouse_for_financial_services_dim_team
10. enterprise_data_warehouse_for_financial_services_dim_region
11. enterprise_data_warehouse_for_financial_services_audit_ops_ingest
12. enterprise_data_warehouse_for_financial_services_ref_runbooks
13. enterprise_data_warehouse_for_financial_services_stage_incidents
14. enterprise_data_warehouse_for_financial_services_fact_incident_metrics
15. enterprise_data_warehouse_for_financial_services_dim_priority
16. enterprise_data_warehouse_for_financial_services_ref_maintenance_windows
17. enterprise_data_warehouse_for_financial_services_audit_recon
18. enterprise_data_warehouse_for_financial_services_stage_trimmed_logs
19. enterprise_data_warehouse_for_financial_services_ref_retention_policy
20. enterprise_data_warehouse_for_financial_services_dim_status

ER Diagram (ASCII):

enterprise_data_warehouse_for_financial_services_fact_logs (log_id, service_id, instance_id, log_level, message_ts)
  |-- service_id --> enterprise_data_warehouse_for_financial_services_dim_service(service_id)
  |-- instance_id --> enterprise_data_warehouse_for_financial_services_dim_instance(instance_id)

---

### Source C: Governance & Catalog (Source: `enterprise_data_warehouse_for_financial_services_gov`)

Tables (20):
1. enterprise_data_warehouse_for_financial_services_stg_catalog
2. enterprise_data_warehouse_for_financial_services_raw_catalog
3. enterprise_data_warehouse_for_financial_services_dim_dataset
4. enterprise_data_warehouse_for_financial_services_dim_owner
5. enterprise_data_warehouse_for_financial_services_dim_tag
6. enterprise_data_warehouse_for_financial_services_ref_policies
7. enterprise_data_warehouse_for_financial_services_fact_data_quality
8. enterprise_data_warehouse_for_financial_services_stage_lineage
9. enterprise_data_warehouse_for_financial_services_dim_classification
10. enterprise_data_warehouse_for_financial_services_dim_sensitivity
11. enterprise_data_warehouse_for_financial_services_audit_policies
12. enterprise_data_warehouse_for_financial_services_ref_sla
13. enterprise_data_warehouse_for_financial_services_stage_certifications
14. enterprise_data_warehouse_for_financial_services_fact_issues
15. enterprise_data_warehouse_for_financial_services_dim_remediation_team
16. enterprise_data_warehouse_for_financial_services_ref_controls
17. enterprise_data_warehouse_for_financial_services_audit_certification
18. enterprise_data_warehouse_for_financial_services_stage_policy_changes
19. enterprise_data_warehouse_for_financial_services_ref_standards
20. enterprise_data_warehouse_for_financial_services_dim_status

ER Diagram (ASCII):

enterprise_data_warehouse_for_financial_services_fact_data_quality (dq_id, dataset_id, check_name, check_status, checked_ts)
  |-- dataset_id --> enterprise_data_warehouse_for_financial_services_dim_dataset(dataset_id)

---

### Source D: Cost, Billing & Usage (Source: `enterprise_data_warehouse_for_financial_services_cost`)

Tables (20):
1. enterprise_data_warehouse_for_financial_services_stg_billing_records
2. enterprise_data_warehouse_for_financial_services_raw_billing
3. enterprise_data_warehouse_for_financial_services_dim_cost_center
4. enterprise_data_warehouse_for_financial_services_dim_resource_type
5. enterprise_data_warehouse_for_financial_services_dim_region
6. enterprise_data_warehouse_for_financial_services_ref_price_catalog
7. enterprise_data_warehouse_for_financial_services_fact_cost_usage
8. enterprise_data_warehouse_for_financial_services_stage_allocations
9. enterprise_data_warehouse_for_financial_services_dim_tagging
10. enterprise_data_warehouse_for_financial_services_dim_currency
11. enterprise_data_warehouse_for_financial_services_audit_billing_ingest
12. enterprise_data_warehouse_for_financial_services_ref_discounts
13. enterprise_data_warehouse_for_financial_services_stage_corrections
14. enterprise_data_warehouse_for_financial_services_fact_monthly_costs
15. enterprise_data_warehouse_for_financial_services_dim_billing_account
16. enterprise_data_warehouse_for_financial_services_ref_chargeback_rules
17. enterprise_data_warehouse_for_financial_services_audit_allocations
18. enterprise_data_warehouse_for_financial_services_stage_forecasts
19. enterprise_data_warehouse_for_financial_services_ref_rates
20. enterprise_data_warehouse_for_financial_services_dim_status

ER Diagram (ASCII):

enterprise_data_warehouse_for_financial_services_fact_cost_usage (usage_id, resource_id, cost_amount, currency, start_ts, end_ts)
  |-- resource_id --> enterprise_data_warehouse_for_financial_services_dim_resource_type(resource_id)
  |-- cost_center_id --> enterprise_data_warehouse_for_financial_services_dim_cost_center(cost_center_id)

---

### Source E: Canonical Transactions / Facts (Source: `enterprise_data_warehouse_for_financial_services_txn`)

Tables (20):
1. enterprise_data_warehouse_for_financial_services_stg_transactions
2. enterprise_data_warehouse_for_financial_services_raw_transactions
3. enterprise_data_warehouse_for_financial_services_dim_account
4. enterprise_data_warehouse_for_financial_services_dim_customer
5. enterprise_data_warehouse_for_financial_services_dim_product
6. enterprise_data_warehouse_for_financial_services_ref_exchange_rates
7. enterprise_data_warehouse_for_financial_services_fact_transactions
8. enterprise_data_warehouse_for_financial_services_stage_reconciliations
9. enterprise_data_warehouse_for_financial_services_dim_channel
10. enterprise_data_warehouse_for_financial_services_dim_merchant
11. enterprise_data_warehouse_for_financial_services_audit_txn_ingest
12. enterprise_data_warehouse_for_financial_services_ref_fee_schedule
13. enterprise_data_warehouse_for_financial_services_stage_settlements
14. enterprise_data_warehouse_for_financial_services_fact_settlements
15. enterprise_data_warehouse_for_financial_services_dim_status
16. enterprise_data_warehouse_for_financial_services_ref_limits
17. enterprise_data_warehouse_for_financial_services_audit_recon
18. enterprise_data_warehouse_for_financial_services_stage_adjustments
19. enterprise_data_warehouse_for_financial_services_fact_balance_snapshots
20. enterprise_data_warehouse_for_financial_services_dim_time

ER Diagram (ASCII):

enterprise_data_warehouse_for_financial_services_fact_transactions (transaction_id, account_id, amount, currency, txn_type, posted_ts)
  |-- account_id --> enterprise_data_warehouse_for_financial_services_dim_account(account_id)
  |-- customer_id --> enterprise_data_warehouse_for_financial_services_dim_customer(customer_id)
  |-- product_id --> enterprise_data_warehouse_for_financial_services_dim_product(product_id)

Common guidance:
- Always keep an immutable staging/raw zone for auditable ingestion.
- Use `audit_*` tables and checksums for reconciliation between source and target facts.
- Implement SCD patterns for dimensions where history is required.
- Register datasets in a data catalog and apply RBAC and PII protections as required.

